trigger:
  - cccs-master

variables:
  containerRegistry: uchimera
  imageRepository: 'cccs/che-plugin-registry'
  buildTimestamp: $[format('{0:yyyyMMddHHmmss}', pipeline.startTime)]
  version: 7.24.1

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: Login to $(containerRegistry)
  inputs:
    containerRegistry: $(containerRegistry)
    command: 'login'
- task: Docker@2
  displayName: Build offline image
  inputs:
    command: build
    buildContext: $(Build.Repository.LocalPath)
    repository: $(imageRepository)
    dockerfile: $(Build.SourcesDirectory)/build/dockerfiles/Dockerfile
    arguments: --build-arg PATCHED_IMAGES_TAG=$(version) --build-arg USE_DIGESTS=false --target offline-registry
    tags: |
      $(version) 
- task: Docker@2
  displayName: Push image to container registry
  inputs:
    containerRegistry: $(containerRegistry)
    command: push
    repository: $(imageRepository)
    tags: |
      $(version) 
